import React, { useState, useEffect } from 'react';
import { useWeb3 } from '../context/Web3Context';
import { MerkleTree } from '../utils/merkleTree';
import { CheckCircle, Search, ShieldCheck, XCircle, AlertTriangle, Loader2 } from 'lucide-react';
import confetti from 'canvas-confetti';

export const VerifySection: React.FC = () => {
  const { verifyProof, checkRootExists, registerRoot, mode, autofillVerifyData } = useWeb3();
  const [fileToVerify, setFileToVerify] = useState<File | null>(null);
  const [rootHash, setRootHash] = useState('');
  const [proofJson, setProofJson] = useState('');
  const [positionsJson, setPositionsJson] = useState('');
  const [verificationResult, setVerificationResult] = useState<boolean | null>(null);
  const [isVerifying, setIsVerifying] = useState(false);
  const [isGeneratingTest, setIsGeneratingTest] = useState(false);
  const [leafHashToHighlight, setLeafHashToHighlight] = useState<string>('');

  // Synchronize autofill data if available
  useEffect(() => {
    if (autofillVerifyData) {
      setRootHash(autofillVerifyData.rootHash);
      setProofJson(JSON.stringify(autofillVerifyData.proof));
      setPositionsJson(JSON.stringify(autofillVerifyData.positions));
      setVerificationResult(null);
    }
  }, [autofillVerifyData]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFileToVerify(e.target.files[0]);
      setVerificationResult(null);
    }
  };

  const handleVerify = async () => {
    if (!fileToVerify || !rootHash || !proofJson || !positionsJson) return;

    setIsVerifying(true);
    setVerificationResult(null);

    try {
      const proof = JSON.parse(proofJson);
      const positions = JSON.parse(positionsJson);
      const leafData = `${fileToVerify.name}-${fileToVerify.size}-${fileToVerify.lastModified}`;
      const leafHash = MerkleTree.hash(leafData);
      
      setLeafHashToHighlight(leafHash);

      const isValid = await verifyProof(rootHash, leafHash, proof, positions);
      setVerificationResult(isValid);

      if (isValid) {
        confetti({
          particleCount: 100,
          spread: 70,
          origin: { y: 0.6 }
        });
      }
    } catch (err) {
      console.error(err);
      alert("Verification failed or reverted: " + (err as Error).message);
      setVerificationResult(false);
    } finally {
      setIsVerifying(false);
    }
  };

  // Helper to generate a proof and auto-register it to the blockchain so tests pass
  const generateTestProof = async () => {
    if (!fileToVerify) {
        alert("Select a file first to generate a test proof!");
        return;
    }
    
    setIsGeneratingTest(true);
    setVerificationResult(null);

    try {
      const leafData = `${fileToVerify.name}-${fileToVerify.size}-${fileToVerify.lastModified}`;
      const mt = new MerkleTree([leafData, "some-other-doc-1", "some-other-doc-2"]);
      const root = mt.getRootHash();
      const { proof, positions } = mt.getProof(MerkleTree.hash(leafData));

      // Make sure the root actually exists on the blockchain (mock or live)
      const exists = await checkRootExists(root);
      if (!exists) {
        if (mode === 'live') {
          const confirmRegister = confirm(
            `The test Merkle root (${root.substring(0, 10)}...) is not yet registered on the blockchain.\n\n` +
            `Would you like to register it now? This requires MetaMask confirmation and some test ETH.`
          );
          if (!confirmRegister) {
            setIsGeneratingTest(false);
            return;
          }
        }
        
        // Register the root hash
        await registerRoot(root, `Autogenerated test root for ${fileToVerify.name}`);
      }

      setRootHash(root);
      setProofJson(JSON.stringify(proof));
      setPositionsJson(JSON.stringify(positions));
    } catch (err) {
      console.error(err);
      alert("Failed to auto-register test root: " + (err as Error).message);
    } finally {
      setIsGeneratingTest(false);
    }
  };

  // Check if selected file matches the name of autofilled payload
  const hasFileNameMismatch = autofillVerifyData && fileToVerify && fileToVerify.name !== autofillVerifyData.fileName;

  return (
    <div className="glass-panel" id="verify-section">
      <h2 style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
        <ShieldCheck size={24} color="var(--success)" />
        Verify File
      </h2>
      <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem', fontSize: '0.9rem' }}>
        Provide a file, the registered root hash, and its Merkle proof to independently verify its integrity against the blockchain.
      </p>

      {/* Visual notification for autofills */}
      {autofillVerifyData && (
        <div style={{ 
          background: 'rgba(56, 189, 248, 0.1)', 
          border: '1px solid var(--primary)', 
          padding: '0.75rem', 
          borderRadius: '0.5rem', 
          marginBottom: '1.25rem', 
          fontSize: '0.85rem' 
        }}>
          <div>
            <strong>Autofilled Verification Data</strong> for file:
          </div>
          <div style={{ color: 'var(--primary)', fontWeight: 'bold', marginTop: '0.25rem' }}>
            {autofillVerifyData.fileName}
          </div>
          {!fileToVerify ? (
            <div style={{ marginTop: '0.5rem', color: 'var(--text-secondary)', fontSize: '0.8rem' }}>
              👉 Please select the file above/below to run verification.
            </div>
          ) : hasFileNameMismatch ? (
            <div style={{ marginTop: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--error)', fontSize: '0.8rem', fontWeight: 'bold' }}>
              <AlertTriangle size={14} /> Selected file name does not match autofill file!
            </div>
          ) : (
            <div style={{ marginTop: '0.5rem', color: 'var(--success)', fontSize: '0.8rem', fontWeight: 'bold' }}>
              ✓ Matching file selected. Ready to verify.
            </div>
          )}
        </div>
      )}

      <div style={{ marginBottom: '1rem' }}>
        <input 
          type="file" 
          onChange={handleFileChange} 
          className="input-field"
          style={{ background: 'rgba(0,0,0,0.1)' }}
        />
        {fileToVerify && (
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                <span style={{ fontSize: '0.85rem', color: 'var(--primary)' }}>Selected: {fileToVerify.name}</span>
                <button 
                  onClick={generateTestProof} 
                  disabled={isGeneratingTest}
                  className="btn btn-secondary" 
                  style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}
                >
                  {isGeneratingTest && <Loader2 size={12} className="spinner" />}
                  {isGeneratingTest ? 'Registering on-chain...' : 'Auto-Fill Test Proof'}
                </button>
            </div>
        )}
      </div>

      <input 
        type="text" 
        placeholder="Registered Root Hash (0x...)" 
        className="input-field"
        value={rootHash}
        onChange={e => setRootHash(e.target.value)}
      />

      <input 
        type="text" 
        placeholder='Proof Hashes Array (e.g. ["0x..."])' 
        className="input-field"
        value={proofJson}
        onChange={e => setProofJson(e.target.value)}
      />

      <input 
        type="text" 
        placeholder='Positions Array (e.g. [true, false])' 
        className="input-field"
        value={positionsJson}
        onChange={e => setPositionsJson(e.target.value)}
      />

      <button 
        className="btn" 
        style={{ width: '100%', background: 'var(--success)', color: '#0f172a' }}
        onClick={handleVerify}
        disabled={isVerifying || isGeneratingTest || !fileToVerify || !rootHash || !proofJson || !positionsJson}
      >
        <Search size={18} />
        {isVerifying ? 'Verifying on-chain...' : 'Verify Integrity'}
      </button>

      {verificationResult !== null && (
        <div style={{
          marginTop: '1.5rem',
          padding: '1rem',
          borderRadius: '0.5rem',
          background: verificationResult ? 'rgba(16, 185, 129, 0.1)' : 'rgba(239, 68, 68, 0.1)',
          border: `1px solid ${verificationResult ? 'var(--success)' : 'var(--error)'}`,
          display: 'flex',
          alignItems: 'center',
          gap: '1rem'
        }}>
          {verificationResult ? (
            <CheckCircle size={32} color="var(--success)" />
          ) : (
            <XCircle size={32} color="var(--error)" />
          )}
          <div>
            <div style={{ fontWeight: 'bold', color: verificationResult ? 'var(--success)' : 'var(--error)' }}>
              {verificationResult ? 'Verification Successful' : 'Verification Failed'}
            </div>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
              {verificationResult 
                ? 'The file matches the registered Merkle root. Its integrity and timestamp are confirmed.' 
                : 'The file or proof is invalid. It does not match the registered root.'}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
